### ISSUE TITLE
Note on misuse

### ISSUE THREAD

**Issue by Pacerier** [anonyco/Javascript-Fast-Light-Map-WeakMap-JS-Polyfill#3]
Note that weakmaps should only be used when you want a memory-sensitive cache. If you want to do data&ndash;object tuples, Javascript provides [6 ways of doing so](https://stackoverflow.com/questions/29413222/what-are-the-actual-uses-of-es6-weakmap/46244159#comment79534889_29416340).

Instead of:
```
    var myMap = new WeakMap(), longString = 'some random strang ', i=100e+6;
    
    while (i--)
        myMap.set({}, longString += i)
    
    console.log(longString.length * myMap.length)
```
..use:
```
var longString = 'some random strang ';
var i=100e+6;
    
    let long_string_key = Symbol();
    while (i--)
        ({})[long_string_key] = longString += i;
    
    console.log(longString.length * 0)
```
Weakmaps not needed: Data is unreferenced on object unreference.

**Comment by anonyco** [comment]
Yes, you are correct that in browsers with native WeakMap support, those code snippets are practicly identical. However, please read the surrounding context before opening an issue. The first snippet is only an example of something that would in fact be referenced and consume lots of memory in a browser whose global WeakMap object is polyfilled by this polyfill.

Also, according to my current knowledge, using symbols to create custom keys will be less efficient than using native Weak Maps because symbols used in the ways above function in a similar manner to Weak Maps (especially in the internal implementation of them), however symbols also carry the extra overhead of having to allocate memory for a new object and the overhead associated with that such that it takes extra time to get the symbol of an object for usage as a key than directly using the object as a key in Weak Maps. If you have knowledge that conflicts with this, then I would be very happy if you could share it with me (as a comment). I always love learning new things, and am always open ears for them if you give a rational explanation for them.

So, the next time you open an issue, please make at least some attempt to read the surrounding context before you open the issue. Anyways, thank you for your feedback in the hopes it will aid this project. Thank you.
